// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://admvdezboujjxewvcbkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkbXZkZXpib3Vqanhld3ZjYmt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDgxMzAsImV4cCI6MjA2NTQ4NDEzMH0.O6KIa4HbhqUSkjMAjtGLiUipX2-7lAZp7zptZ3Uc4TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);